apiVersion: v1
kind: PersistentVolume
metadata:
  name: dropin-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /nfs/dropin
    server: 192.168.10.104